---
source_folder: '/vagrant/bpm/4.2'

installation_folder: '/vagrant/bpm_installation'

installer_archives:
  - 'TIB_amx-bpm_4.2.0_linux24gl23_x86_64.zip'

tibco_home: '/home/vagrant/tibco'
tibco_env_name: 'TIBCO-HOME'
tibco_config_home: '/home/vagrant/TIBCO_HOME'

env_name: 'amx-bpm'
